name: Build and Release

on:
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - platform: linux
            arch: '386'
          - platform: linux
            arch: 'amd64'
          - platform: linux
            arch: 'arm'
          - platform: linux
            arch: 'arm64'

    steps:
      - uses: actions/checkout@v2

      - name: Docker Pull
        id: docker-pull
        run: |
          docker pull dnsunlockcom/build-go-1.22.5

      - name: Build
        id: build
        run: |
          docker build -t my-golang-app .

      - name: Docker Run
        id: run
        run: |
          docker run --name temp-container my-golang-app 

      - name: Copy file
        id: copy-file
        run: |
          docker cp temp-container:/app/unlock_test.so ./UnlockTest-${{ matrix.arch }}.so

      - name: Compute hash
        id: compute-hash
        run: |
          md5sum ./UnlockTest-${{ matrix.arch }}.so | cut -d ' ' -f 1 > ./UnlockTest-${{ matrix.arch }}.so.md5sum

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        if: github.event_name == 'release'
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: |
            ./UnlockTest-${{ matrix.arch }}.so
          tag: ${{ github.ref }}
          file_glob: true
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        if: github.event_name == 'release'
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: |
            ./UnlockTest-${{ matrix.arch }}.so.md5sum
          tag: ${{ github.ref }}
          file_glob: true
